# When /annihilation start command is run, the delay before starting phase 1 in seconds
start-delay: 120
#
# Phase length in seconds (Phase 5 is perpetual)
phase-period: 600
#
# When the game ends, the delay before resetting the game
restart-delay: 120
#
# Amount of players required to start the game
requiredToStart: 20
#
# Build Distance from Nexus
build: 10
#
# Delay in minutes to respawn the bosses after death
bossRespawnDelay: 10
#
# Delay in minutes to respawn the witchs after death
witchRespawnDelay: 5
#
# The last phase players can join a team
lastJoinPhase: 3
#
#Ending game
Force-end:
  hours: 2
  minutes: 00

#
# El uso de BD es obligatorio
# El tipo puede ser MySQL, SQLite, MongoDB
Database:
  type: "MySQL"
  host: "localhost"
  port: 3306
  name: "anni"
  user: "root"
  pass: "root"

# Enable the custom MOTD
enableMotd: true
#
#
# Custom MOTD - Values you can use
# %PHASE% %TIME% %PLAYERCOUNT% %MAXPLAYERS%
# %GREENNEXUS% %REDNEXUS% %BLUENEXUS% %YELLOWNEXUS%
# %GREENCOUNT% %REDCOUNT% %BLUECOUNT% %YELLOWCOUNT%
motd: '&cPhase: &5%PHASE%'
motd-lobby: '&5Lobby'
motd-start: '&6Phase: &2%PHASE%'

#
#Economy setup
Exp-player-kill: 20
Exp-boss-kill: 300
Money-nexus-hit: 5
Money-nexus-kill: 50
Money-player-kill: 30
Money-boss-kill: 80
Money-win: 150

#Boss loot settings
Boss-loot:
  Item-Nb: 6
  Item0:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_HELMET
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 1
        OXYGEN: 3
      display-name: '§eOxyger'
      lore:
        - '§7Power of oxygen'
        - '§eUnique Item'
      repair-cost: 4
  Item1:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_HELMET
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
        OXYGEN: 3
      display-name: '§6Oxyger II'
      lore:
        - '§7Power of oxygen II'
        - '§5Rare Item'
      repair-cost: 4
  Item2:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_LEGGINGS
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
      display-name: '§3Anti sharp'
      lore:
        - '§7Better than normal.'
        - '§eUnique Item'
      repair-cost: 2
  Item3:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_BOOTS
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 2
        PROTECTION_FALL: 4
      display-name: '§aFly boots'
      lore:
        - '§7Less damage of falling.'
        - '§5Rare Item'
      repair-cost: 2
  Item4:
    ==: org.bukkit.inventory.ItemStack
    type: BOW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        ARROW_INFINITE: 1
      display-name: '§aInfinite Shooter'
      lore:
        - '§7This bow is great.'
        - '§eUnique Item'
      repair-cost: 4
  Item5:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        DAMAGE_ALL: 3
      display-name: '§aBlood finder'
      lore:
        - '§7Sharpness is your brother.'
        - '§eUnique Item'
      repair-cost: 2
  Item6:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_CHESTPLATE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
      display-name: '§2§lTroll plate'
      lore:
        - '§7Defending is smarter'
        - '§eUnique Item'
      repair-cost: 2