# When /annihilation start command is run, the delay before starting phase 1 in seconds
start-delay: 120
#
# Phase length in seconds (Phase 5 is perpetual)
phase-period: 600
#
# When the game ends, the delay before resetting the game
restart-delay: 120
#
# Amount of players required to start the game
requiredToStart: 20
#
# Build Distance from Nexus
build: 10
#
# Delay in minutes to respawn the bosses after death
bossRespawnDelay: 10
#
# Delay in minutes to respawn the witches after death
witchRespawnDelay: 5
#
# The last phase players can join a team
lastJoinPhase: 3
#
# Ending game
ForceGameEnding: true
Force-end:
  hours: 2
  minutes: 00
#
# Team prefix
# With this the TEAMS_PREFIX translations should appear before the player name
useTeamPrefix: true
#
# Commands after finish
# If set true, you can execute a set of commands when every game finish
userCommandsOnFinish: false
commands:
  - "Your command"
#
# Bungee config
# With this you can set a custom Item and send the player to a custom server using Bungee
enableBungeeCommunication: false
Bungee:
  server: "lobby"
  item: "RED_BED"
#
# The DB usage is mandatory
# The available types are MySQL, SQLite, MongoDB
# MySQL Configuration
Database:
  type: "MySQL"
  host: "your_host_url"
  port: 3306
  name: "your_db_name"
  user: "your_username"
  pass: "your_password"
  useSSL: true
  keystorePassword: "your_keystore_password"

# SQLite Configuration
#Database:
#  type: "SQLite"

# MongoDB Configuration
#Database:
#  type: "MongoDB"
#  host: "localhost"
#  port: 3306
#  name: "anni"
#  user: "root"
#  pass: "root"

# Enable the custom MOTD
enableMotd: true
#
#
# Custom MOTD - Values you can use
# %PHASE% %TIME% %PLAYERCOUNT% %MAXPLAYERS%
# %GREENNEXUS% %REDNEXUS% %BLUENEXUS% %YELLOWNEXUS%
# %GREENCOUNT% %REDCOUNT% %BLUECOUNT% %YELLOWCOUNT%
motd: '&cPhase: &5%PHASE%'
motd-lobby: '&5Lobby'
motd-start: '&6Phase: &2%PHASE%'

#
#Economy setup
Exp-player-kill: 20
Exp-boss-kill: 300
Money-nexus-hit: 5
Money-nexus-kill: 50
Money-player-kill: 30
Money-boss-kill: 80
Money-win: 150
