name: Annihilation
main: com.hyuchiha.Annihilation.Main
authors: [Hyuchiha]
softdepend: [Vault, Multiverse-Core, ProtocolLib]
version: 1.2.0
commands:
  anni:
    description: All the commands for games
    aliases: w
  team:
    description: Team command for Annihilation
    aliases: t
  vote:
    description: Put a vote for a map
    aliases: v
  stats:
    description: Comando para listar estadisticas de un jugador
    aliases: s
  top:
    description: Comando para listar el top de kills, deaths, etc...
    aliases: p
  class:
    description: Selects your kit
    aliases: c
  star:
    description: Only for testing
    aliases: st